spring:
 main:
  allow-bean-definition-overriding: true
 
 security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

 application:
  name: gatewayserver
 config:
  import: "configserver:http://localhost:8071/"
 cloud:
  gateway:
   discovery:
    locator:
      enabled: true
      lowerCaseServiceId: true
#   httpclient:
#    connect-timeout: 10000
#    response-timeout: 1s
 data:
    redis:
      port: 6379
      host: localhost
      connect-timeout: 2s

server:
 port: 8072

management:
 endpoints:
  web:
   exposure:
    include: "*"
 endpoint:
  health:
   probes:
     enabled: true
  shutdown:
    access: UNRESTRICTED
  gateway:
    access: UNRESTRICTED

eureka:
 instance:
  prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
    defaultZone: "http://localhost:8070/eureka/"

resilience4j.circuitbreaker:
    configs:
     default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 5000ms

 
logging:
  level:
    org:
     springframework:
      security.web.server: DEBUG