spring:
 jpa:
  show-sql: true
 sql:
  init:
   mode: always
 application:
  name: jpa-practice
 datasource:
  url: jdbc:mysql://localhost:3306/jpademo
  username: root
  password: password
logging:
  level:
   org:
    springframework: info