spring:
 application:
  name: gatewayserver
 cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
 config:
  import: "configserver:http://localhost:8071/"
eureka:
 instance:
  prefer-ip-address: true
 client:
  fetch-registry: true
  register-with-eureka: true
server:
 port: 8072
 
base:
 url: "http://localhost:8072/"
logging:
  level: 
    '[org.springframework]': DEBUG
    